version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    container_name: nginx_project
    depends_on:
      - app
  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
        -   db
    container_name: app_project
  db:
    image: postgres:15
    restart: always
    volumes:
        -   ./tmp/db:/var/lib/postgres
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: blog
    ports:
        -   "5432:5432"
    container_name: db_project

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: gonchikova_00@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 123
