version: '3'
services:
  app:
    container_name: app_project
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
        -   db

  db:
    image: postgres:15
    container_name: db_project
    restart: always
    volumes:
        -   ./tmp/db:/var/lib/postgres
    env_file:
      - ./var.env
    ports:
        -   "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: gonchikova_00@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 123
